### ISSUE TITLE
AttributeError: module '_Box2D' has no attribute 'RAND_LIMIT_swigconstant'

### ISSUE THREAD

**Issue by impactro** [inteligenciamilgrau/videos_tutoriais#1]
Ola, gostei do vídeo e quero testar o código.
Mas ao tentar usar e instalar a dependencia do gym, ele pede o box2d
Segui outras dicas, mas no final deu esse erro:
AttributeError: module '_Box2D' has no attribute 'RAND_LIMIT_swigconstant' 

Estou usando Windows 11, e python 3.9.0 (não posso instalar outra versão no momento)

**Comment by inteligenciamilgrau** [comment]
Veja se algum desses items resolve!!
https://stackoverflow.com/questions/50037674/attributeerror-module-box2d-has-no-attribute-rand-limit-swigconstant
