### ISSUE TITLE
problema com "generate"

### ISSUE THREAD

**Issue by soujiang** [inteligenciamilgrau/videos_tutoriais#3]
Hola, tengo el siguiente error en el codigo de elevenlabs, hay un problema con "generate" he buscado soluciones pero no encuentro ninguna, podrias ayudarme?

Olá, estou com o seguinte erro no código da elevenlabs, há um problema com "generate". Tenho procurado soluções, mas não encontro nenhuma. Você poderia me ajudar?

Exception has occurred: ImportError
cannot import name 'generate' from 'elevenlabs' (d:\PROYECTOS_CON_IA\CODIGOS\CREACION_VOCES\env\Lib\site-packages\elevenlabs\__init__.py)
  File "D:\PROYECTOS_CON_IA\CODIGOS\CREACION_VOCES\prueba_2.py", line 2, in <module>
    from elevenlabs import generate, play, voices, set_api_key, save, User, Voice, VoiceSettings
ImportError: cannot import name 'generate' from 'elevenlabs' (d:\PROYECTOS_CON_IA\CODIGOS\CREACION_VOCES\env\Lib\site-packages\elevenlabs\__init__.py)

É deste código:

https://github.com/inteligenciamilgrau/videos_tutoriais/blob/main/elevenLabsApi/eleven_labs.py

**Comment by inteligenciamilgrau** [comment]
Atualizei a lib para a nova versão

**Comment by soujiang** [comment]
Muito obrigado, vou ver como vai e te aviso qualquer coisa.
